// =====================================================================
// src/lib/ansEq.js — echivalența răspunsurilor în BROWSER (exerciții interactive)
// „1/2" = „0,5", „x=3" = „3", „2√3" = „2\\sqrt{3}", „24 cm²" = „24", {2; 3} = {3; 2}.
// OGLINDA lui api/_lib/mathcheck.js → BROWSER_ANS_EQ (sursa unică, injectată și
// în HTML-ul generat de exgen). Testul test/etapa2-mathcheck.test.js verifică
// că cele două copii sunt identice — modifică ACOLO, apoi copiază aici.
// =====================================================================
export const ANS_EQ_SRC = "function ansEq(a,b){\n  function num(s){ s=String(s||'').trim().replace(/\\((-?\\d+(?:\\.\\d+)?)\\)/g,'$1'); var m=/^(-?\\d+(?:\\.\\d+)?)\\s*\\/\\s*(-?\\d+(?:\\.\\d+)?)$/.exec(s); if(m){ var d=parseFloat(m[2]); return d?parseFloat(m[1])/d:NaN; } if(/^-?\\d+(?:\\.\\d+)?$/.test(s)) return parseFloat(s); var r=/^(-?\\d*(?:\\.\\d+)?)\\s*(?:sqrt|√)\\(?(\\d+(?:\\.\\d+)?)\\)?$/.exec(s); if(r){ var c=r[1]===''||r[1]==='-'?(r[1]==='-'?-1:1):parseFloat(r[1]); return c*Math.sqrt(parseFloat(r[2])); } return NaN; }\n  function norm(s){ s=String(s||'').toLowerCase().replace(/\\$/g,'').replace(/\\\\(?:left|right|,|;|!)/g,'').replace(/\\\\(?:d)?frac\\{([^}]*)\\}\\{([^}]*)\\}/g,'($1)/($2)').replace(/\\\\sqrt\\{([^}]*)\\}/g,'sqrt($1)').replace(/\\\\cdot|×|·/g,'*').replace(/\\\\pi|π/g,'pi').replace(/²/g,'^2').replace(/³/g,'^3').replace(/\\^\\{([^}]*)\\}/g,function(m,g){ return /^[\\w.]+$/.test(g)?'^'+g:'^('+g+')'; }).replace(/%/g,'').replace(/(\\d)\\s*(cm|dm|mm|km|m|kg|g|lei|ron|ore|min|s|l)(\\^?[23])?\\s*$/,'$1').replace(/^\\s*[a-z][a-z0-9_]{0,3}\\s*(?:=|∈)\\s*/,'').replace(/(\\d),\\s+(?=[-\\d])/g,'$1;').replace(/(\\d),(\\d)/g,'$1.$2').replace(/\\s+/g,''); return s; }\n  var A=norm(a), B=norm(b); if(A===B) return true;\n  var set=function(s){ var m=/^[\\{\\[\\(](.*)[\\}\\]\\)]$/.exec(s); s=m?m[1]:s; return s.split(/;|și|si/).filter(Boolean).sort(); };\n  if(/[;{]/.test(A)||/[;{]/.test(B)){ var sa=set(A), sb=set(B); if(sa.length!==sb.length) return false; for(var i=0;i<sa.length;i++){ var x=num(sa[i]), y=num(sb[i]); if(!(sa[i]===sb[i]||(!isNaN(x)&&!isNaN(y)&&Math.abs(x-y)<=1e-6*Math.max(1,Math.abs(x))))) return false; } return true; }\n  var x=num(A), y=num(B); if(!isNaN(x)&&!isNaN(y)){ var pa=/%/.test(String(a)), pb=/%/.test(String(b)); var eq=function(u,v){ return Math.abs(u-v)<=1e-6*Math.max(1,Math.abs(u),Math.abs(v)); }; return eq(x,y)||(pa!==pb&&eq(pa?x/100:x, pb?y/100:y)); }\n  return false;\n}";

// eslint-disable-next-line no-new-func
export const ansEq = new Function(ANS_EQ_SRC + "; return ansEq;")();
